# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Spore Servant
email: sporeservant@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Spore Servant publishes Dungeons and Dragons (D&D) related content such as
  encounters, adventures, quests.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sporeservant.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sporeservant
github_username: sporeservant 
facebook_username: sporeservant
instagram_username: spore.servant

# NOTE: Pending eligibility with enough followers for a custom domain, youtube, g+.
googleplus_username: sporeservant # u/1/107755631611664498476
youtube_username: sporeservant
youtube_url: channel/UChqZRjwUf5mCHfUz1yZ3eWw 
googleplus_url: u/1/107755631611664498476

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
